name: Build Hugo Site

on:
  push:
    branches: ["docs"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_0.120.4_Linux-64bit.deb
          sudo dpkg -i hugo_0.120.4_Linux-64bit.deb

      - name: Build site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: public
